version: '3.7'

services:

  employee_db:
    image: mysql:9.4.0
    ports:
      - "3307:3306"
    env_file: .env
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - connections
    volumes:
      - employees_db:/var/lib/mysql

  department_db:
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgreuser
      POSTGRES_DB: departments
    networks:
      - connections
    volumes:
      - department_db:/var/lib/postgresql/data

  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - connections

  config-server:
    build: ./config-server/
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka/
    ports:
      - "8088:8088"
    networks:
      - connections
    depends_on:
      - service-registry

  employee-service:
    build: ./employee-service/
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka/
      DB_URL: jdbc:mysql://employee_db:3306/employee?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: mysqluser
      DB_PASSWORD: 1234
    ports:
      - "8082:8082"
    networks:
      - connections
    depends_on:
      - config-server
    restart: always

  department-service:
    build: ./department-service/
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka/
      DB_URL: jdbc:postgresql://department_db:5432/departments
      DB_USER: postgreuser
      DB_PASSWORD: admin
    ports:
      - "8083:8083"
    networks:
      - connections
    depends_on:
      - config-server
    restart: always

  api-gateway:
    build: ./api-gateway/
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka/
    ports:
      - "8060:8060"
    networks:
      - connections
    depends_on:
      - config-server
      - service-registry
    restart: always

volumes:
  employees_db:
  department_db:
networks:
  connections:

